### ISSUE TITLE
Bone torches do not have a localized name

### ISSUE THREAD

**Issue by WolfieWaffle** [BuiltBrokenModding/SBM-BoneTorch#3] opened 2016-06-09 17:30 UTC
In the most recent version, bone torches have the name "tile.null.name".

**Comment by dmodoomsirius** [comment] 2016-06-09 20:14
The most recent version being the 1.9.4 version right?

**Comment by DarkGuardsman** [comment] 2016-06-09 20:33
I'll look into this later today and see what is the cause

**Comment by dmodoomsirius** [comment] 2016-06-09 23:05
is this placed in world or inventory?

**Comment by kolatra** [comment] 2016-06-09 23:25
I just forgot to set the unlocalized name for the Bone Torch in the Block class, it's not done automatically anymore for some reason. 

Fixed now. :)

**Closed as completed by kolatra** 2016-06-09 23:25 UTC
Labels: bug
